version: '3.8'

services:
  task-service:
    image: nyura-task-service:0.0.1
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      USER_SERVICE_URL: http://host.docker.internal:8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      REDIS_DATABASE: 0
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB: taskdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      ACCESS_TOKEN_SECRET: "b858HK56DUuxGraUtFSj4KA/ysWxcenqZ3M1hovR8p2zjCXzOyYgn6V++2JT1Ph3"