server:
  port: 8081

spring:
  application:
    name: task-service

  cache:
    type: redis
    ttl: 30m
  data:
    redis:
      host: localhost
      port: 6379
      password: <your-password-if-any>
      database: 0
      timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      group-id: task-service
      auto-offset-reset: earliest
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.nyura.kamaz.*"
        spring.json.type.mapping: dev.nyura.kamaz.user.dto.UserKafkaMessage:dev.nyura.kamaz.task.kafka.UserKafkaMessage

logging:
  level:
    org.springframework.web: DEBUG
    dev.nyura.kamaz.task: DEBUG

services:
  user:
    url: http://localhost:8080

security:
  jwt:
    secret: "b858HK56DUuxGraUtFSj4KA/ysWxcenqZ3M1hovR8p2zjCXzOyYgn6V++2JT1Ph3"
    expiration: 1d

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs